// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fairelescourses/models/shopping_list.dart';
import 'package:fairelescourses/models/supermarket.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ShoppingItemAdapter());
    registerAdapter(ShoppingListAdapter());
    registerAdapter(SupermarketAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ShoppingItemAdapter());
    registerAdapter(ShoppingListAdapter());
    registerAdapter(SupermarketAdapter());
  }
}
